CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'fsalazar'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'fsalazar'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345';